// 27 Indian Languages Metadata & Translation Matrix for SatQuery AI
export const INDIAN_LANGUAGES = [
  {
    id: "en",
    code: "en",
    name: "English",
    nativeName: "English",
    script: "Latin",
    category: "Official",
    region: "Global / Pan-India",
    speakers: "128M+",
    flag: "🇮🇳",
    samplePrompt: "Identify flooded agricultural fields and urban expansion in Earth observation data.",
    welcome: "Welcome to SatQuery AI",
    tagline: "Precision Multi-Modal Earth Observation & Spatial Intelligence"
  },
  {
    id: "hi",
    code: "hi",
    name: "Hindi",
    nativeName: "हिन्दी",
    script: "Devanagari (देवनागरी)",
    category: "Scheduled (8th Schedule)",
    region: "North & Central India",
    speakers: "528M",
    flag: "🇮🇳",
    samplePrompt: "पृथ्वी अवलोकन डेटा में बाढ़ग्रस्त कृषि क्षेत्रों और शहरी विस्तार की पहचान करें।",
    welcome: "सैटक्वेरी एआई में आपका स्वागत है",
    tagline: "सटीक बहु-मोडल पृथ्वी अवलोकन एवं स्थानिक बुद्धिमत्ता"
  },
  {
    id: "bn",
    code: "bn",
    name: "Bengali",
    nativeName: "বাংলা",
    script: "Bengali (বাংলা লিপি)",
    category: "Scheduled (8th Schedule)",
    region: "West Bengal, Tripura, Assam",
    speakers: "97M",
    flag: "🇮🇳",
    samplePrompt: "উপগ্রহ তথ্যে প্লাবিত কৃষি জমি এবং নগর সম্প্রসারণ চিহ্নিত করুন।",
    welcome: "স্যাটকোয়েরি এআই-তে স্বাগতম",
    tagline: "সঠিক বহু-মোডাল পৃথিবী পর্যবেক্ষণ এবং স্থানিক বুদ্ধিমত্তা"
  },
  {
    id: "mr",
    code: "mr",
    name: "Marathi",
    nativeName: "मराठी",
    script: "Devanagari (देवनागरी)",
    category: "Scheduled (8th Schedule)",
    region: "Maharashtra, Goa",
    speakers: "83M",
    flag: "🇮🇳",
    samplePrompt: "उपग्रह डेटामध्ये पूरग्रस्त शेती जमीन आणि नागरी विस्तार ओळखा।",
    welcome: "सॅटक्वेरी एआय मध्ये आपले स्वागत आहे",
    tagline: "अंतराळ डेटा आणि अचूक भूप्रदेश विश्लेषण बुद्धिमत्ता"
  },
  {
    id: "te",
    code: "te",
    name: "Telugu",
    nativeName: "తెలుగు",
    script: "Telugu (తెలుగు లిపి)",
    category: "Scheduled (8th Schedule)",
    region: "Andhra Pradesh, Telangana",
    speakers: "81M",
    flag: "🇮🇳",
    samplePrompt: "ఉపగ్రహ డేటాలో వరదలు ముంచెత్తిన వ్యవసాయ భూములు మరియు పట్టణ విస్తరణను గుర్తించండి.",
    welcome: "సాట్‌క్వెరీ AI కి స్వాగతం",
    tagline: "ఖచ్చితమైన సరిహద్దుల ఉపగ్రహ పరిశీలన & భూమి విశ్లేషణ"
  },
  {
    id: "ta",
    code: "ta",
    name: "Tamil",
    nativeName: "தமிழ்",
    script: "Tamil (தமிழ் எழுத்து)",
    category: "Scheduled (8th Schedule)",
    region: "Tamil Nadu, Puducherry",
    speakers: "69M",
    flag: "🇮🇳",
    samplePrompt: "செயற்கைக்கோள் தரவில் வெள்ளத்தால் பாதிக்கப்பட்ட விவசாய நிலங்கள் மற்றும் நகர விரிவாக்கத்தைக் கண்டறியவும்.",
    welcome: "சாட்க்வெரி AI-க்கு வரவேற்கிறோம்",
    tagline: "துல்லியமான பல-மாடல் பூமி கண்காணிப்பு & இடஞ்சார்ந்த அறிவு"
  },
  {
    id: "gu",
    code: "gu",
    name: "Gujarati",
    nativeName: "ગુજરાતી",
    script: "Gujarati (ગુજરાતી લિપિ)",
    category: "Scheduled (8th Schedule)",
    region: "Gujarat, Daman & Diu",
    speakers: "55M",
    flag: "🇮🇳",
    samplePrompt: "ઉપગ્રહ ડેટામાં પૂરગ્રસ્ત કૃષિ જમીન અને શહેરી વિસ્તરણ ઓળખો.",
    welcome: "સેટક્વેરી AI માં આપનું સ્વાગત છે",
    tagline: "ચોક્કસ પૃથ્વી અવલોકન અને ભૌગોલિક સ્થાનિક બુદ્ધિમત્તા"
  },
  {
    id: "kn",
    code: "kn",
    name: "Kannada",
    nativeName: "ಕನ್ನಡ",
    script: "Kannada (ಕನ್ನಡ ಲಿಪಿ)",
    category: "Scheduled (8th Schedule)",
    region: "Karnataka",
    speakers: "44M",
    flag: "🇮🇳",
    samplePrompt: "ಉಪಗ್ರಹ ಡೇಟಾದಲ್ಲಿ ಪ್ರವಾಹ ಪೀಡಿತ ಕೃಷಿ ಭೂಮಿ ಮತ್ತು ನಗರ ವಿಸ್ತರಣೆಯನ್ನು ಗುರುತಿಸಿ.",
    welcome: "ಸ್ಯಾಟ್‌ಕ್ವೆರಿ AI ಗೆ ಸುಸ್ವಾಗತ",
    tagline: "ನಿಖರವಾದ ಉಪಗ್ರಹ ಭೂ ವೀಕ್ಷಣೆ ಮತ್ತು ಭೌಗೋಳಿಕ ತಂತ್ರಜ್ಞಾನ"
  },
  {
    id: "ml",
    code: "ml",
    name: "Malayalam",
    nativeName: "മലയാളം",
    script: "Malayalam (മലയാളലിപി)",
    category: "Scheduled (8th Schedule)",
    region: "Kerala, Lakshadweep",
    speakers: "38M",
    flag: "🇮🇳",
    samplePrompt: "ഉപഗ്രഹ ഡാറ്റയിൽ വെള്ളപ്പൊക്ക ബാധിത കാർഷിക ഭൂമിയും നഗര വികസനവും തിരിച്ചറിയുക.",
    welcome: "സാറ്റ്ക്വറി എഐ-ലേക്ക് സ്വാഗതം",
    tagline: "കൃത്യമായ ഭൂനിരീക്ഷണവും ബഹിരാകാശ വിശകലന സാങ്കേതികവിദ്യയും"
  },
  {
    id: "or",
    code: "or",
    name: "Odia",
    nativeName: "ଓଡ଼ିଆ",
    script: "Odia (ଓଡ଼ିଆ ଲିପି)",
    category: "Scheduled (8th Schedule)",
    region: "Odisha",
    speakers: "37M",
    flag: "🇮🇳",
    samplePrompt: "ଉପଗ୍ରହ ଡାଟାରେ ବନ୍ୟାପ୍ଲାବିତ କୃଷି ଜମି ଏବଂ ସହରାଞ୍ଚଳ ସମ୍ପ୍ରସାରଣ ଚିହ୍ନଟ କରନ୍ତୁ।",
    welcome: "ସ୍ୟାଟକ୍ବେରୀ AI କୁ ସ୍ଵାଗତ",
    tagline: "ସଠିକ୍ ବହୁ-ମୋଡାଲ୍ ପୃଥିବୀ ଅନୁଧ୍ୟାନ ଏବଂ ସ୍ଥାନିକ ବୁଦ୍ଧିମତ୍ତା"
  },
  {
    id: "pa",
    code: "pa",
    name: "Punjabi",
    nativeName: "ਪੰਜਾਬੀ",
    script: "Gurmukhi (ਗੁਰਮੁਖੀ)",
    category: "Scheduled (8th Schedule)",
    region: "Punjab, Chandigarh",
    speakers: "33M",
    flag: "🇮🇳",
    samplePrompt: "ਉਪਗ੍ਰਹਿ ਡਾਟਾ ਵਿੱਚ ਹੜ੍ਹ ਪ੍ਰਭਾਵਿਤ ਖੇਤੀਬਾੜੀ ਜ਼ਮੀਨਾਂ ਅਤੇ ਸ਼ਹਿਰੀ ਪਸਾਰ ਦੀ ਪਛਾਣ ਕਰੋ।",
    welcome: "ਸੈਟਕੁਐਰੀ AI ਵਿੱਚ ਜੀ ਆਇਆਂ ਨੂੰ",
    tagline: "ਸਟੀਕ ਉਪਗ੍ਰਹਿ ਧਰਤੀ ਨਿਰੀਖਣ ਅਤੇ ਭੂਗੋਲਿਕ ਬੁੱਧੀਮਾਨਤਾ"
  },
  {
    id: "ur",
    code: "ur",
    name: "Urdu",
    nativeName: "اردو",
    script: "Perso-Arabic (نستعلیق)",
    category: "Scheduled (8th Schedule)",
    region: "Jammu & Kashmir, Telangana, UP",
    speakers: "50M",
    flag: "🇮🇳",
    samplePrompt: "سیٹلائٹ ڈیٹا میں سیلاب زدہ زرعی زمینوں اور شہری پھیلاؤ کی نشاندہی کریں۔",
    welcome: "سیٹ کوئری اے آئی میں خوش آمدید",
    tagline: "سیٹلائٹ ارضیاتی مشاہدے اور جغرافیائی ذہانت"
  },
  {
    id: "as",
    code: "as",
    name: "Assamese",
    nativeName: "অসমীয়া",
    script: "Assamese (অসমীয়া লিপি)",
    category: "Scheduled (8th Schedule)",
    region: "Assam, North-East",
    speakers: "15M",
    flag: "🇮🇳",
    samplePrompt: "উপগ্ৰহ তথ্যত জলমগ্ন কৃষিভূমি আৰু নগৰীয় সম্প্ৰসাৰণ চিনাক্ত কৰক।",
    welcome: "ছেটকুৱেৰী এআই লৈ স্বাগতম",
    tagline: "সঠিক বহু-মোডেল পৃথিৱী নিৰীক্ষণ আৰু স্থানিক বুদ্ধিমত্তা"
  },
  {
    id: "mai",
    code: "mai",
    name: "Maithili",
    nativeName: "मैथिली",
    script: "Devanagari (देवनागरी)",
    category: "Scheduled (8th Schedule)",
    region: "Bihar, Jharkhand",
    speakers: "14M",
    flag: "🇮🇳",
    samplePrompt: "उपग्रह डेटा मे बाढ़िग्रस्त कृषि क्षेत्र आ शहरी विस्तारक पहचान करू।",
    welcome: "सैटक्वेरी एआई मे स्वागत अछि",
    tagline: "सटीक भू-अवलोकन आ भू-स्थानिक बुद्धिमत्ता"
  },
  {
    id: "sat",
    code: "sat",
    name: "Santhali",
    nativeName: "ᱥᱟᱱᱛᱟᱲᱤ",
    script: "Ol Chiki (ᱚᱞ ᱪᱤᱠᱤ)",
    category: "Scheduled (8th Schedule)",
    region: "Jharkhand, Odisha, WB",
    speakers: "7.3M",
    flag: "🇮🇳",
    samplePrompt: " satellite ᱰᱟᱴᱟ ᱨᱮ ᱵᱟ flat ᱠᱷᱮᱛ ᱟᱨ ᱵᱟ design ᱚᱲᱟᱜ ᱵᱮᱱᱟᱣ ᱪᱤᱱᱦᱟᱹᱣ ᱢᱮ ᱾",
    welcome: "SatQuery AI ᱨᱮ ᱥᱟᱹᱜᱩᱱ ᱫᱟᱨᱟᱢ",
    tagline: " precision ᱥᱮᱨᱢᱟ ᱥᱟᱺᱜᱤᱧ ᱧᱮᱞ ᱟᱨ ᱚᱛ ᱦᱟᱥᱟ ᱵᱟᱰᱟᱭ"
  },
  {
    id: "ks",
    code: "ks",
    name: "Kashmiri",
    nativeName: "کٔشُر / कश्मीरी",
    script: "Perso-Arabic / Devanagari",
    category: "Scheduled (8th Schedule)",
    region: "Jammu & Kashmir",
    speakers: "6.8M",
    flag: "🇮🇳",
    samplePrompt: "سیٹلائٹ ڈیٹا مَنٛز سَیلاب زَدہ زَرعی زَمیٖنَن تہٕ شَہَری پھَیلاؤٕچ نِشاندَہی کَریو۔",
    welcome: "سیٹ کوئری اے آئی یَس مَنٛز خوش آمدید",
    tagline: "دَقیق بَہُ-موڈَل زَمیٖنی مَشاہدہ تہٕ بَہیٖمی زَہانَت"
  },
  {
    id: "ne",
    code: "ne",
    name: "Nepali",
    nativeName: "नेपाली",
    script: "Devanagari (देवनागरी)",
    category: "Scheduled (8th Schedule)",
    region: "Sikkim, West Bengal, Hills",
    speakers: "2.9M",
    flag: "🇮🇳",
    samplePrompt: "उपग्रह डेटामा बाढीग्रस्त कृषि क्षेत्र र सहरी विस्तार पहिचान गर्नुहोस्।",
    welcome: "सैटक्वेरी एआईमा स्वागत छ",
    tagline: "सटीक भू-अवलोकन र भू-स्थानिक बुद्धिमत्ता"
  },
  {
    id: "kok",
    code: "kok",
    name: "Konkani",
    nativeName: "कोंकणी",
    script: "Devanagari (देवनागरी)",
    category: "Scheduled (8th Schedule)",
    region: "Goa, Karnataka, Maharashtra",
    speakers: "2.3M",
    flag: "🇮🇳",
    samplePrompt: "उपग्रह डेटान बुडिल्ली शेतकाम जमीन आनी शाराचो विस्तार वळखा।",
    welcome: "सॅटक्वेरी एआय मध्ये येवकार",
    tagline: "अचूक उपग्रह भूप्रदेश निहाळ आनी बुद्धिमत्ता"
  },
  {
    id: "doi",
    code: "doi",
    name: "Dogri",
    nativeName: "डोगरी",
    script: "Devanagari (देवनागरी)",
    category: "Scheduled (8th Schedule)",
    region: "Jammu & Kashmir, Himachal",
    speakers: "2.6M",
    flag: "🇮🇳",
    samplePrompt: "उपग्रह डेटा च हड़ प्रभावित खेती बाड़ी ज़मीन ते शहरी फैलाव दी पहचान करो।",
    welcome: "सैटक्वेरी एआई च स्वागत ऐ",
    tagline: "सटीक उपग्रह भू-अवलोकन ते स्थानिक समझ"
  },
  {
    id: "mni",
    code: "mni",
    name: "Manipuri (Meitei)",
    nativeName: "ꯃꯩꯇꯩꯂꯣꯟ",
    script: "Meitei Mayek (ꯃꯩꯇꯩ ꯃꯌꯦꯛ)",
    category: "Scheduled (8th Schedule)",
    region: "Manipur, North-East",
    speakers: "1.8M",
    flag: "🇮🇳",
    samplePrompt: "ꯁꯦꯇꯦꯂꯥꯏꯠ ꯗꯦꯇꯥꯗꯥ ꯏꯁꯤꯡ ꯇꯨꯡꯈ꯭ꯔꯕ ꯂꯧꯕꯨꯛ ꯑꯃꯁꯨꯡ ꯁꯍꯔꯒꯤ ꯄꯥꯛ-ꯆꯥꯑꯣꯔꯛꯄ ꯈꯪꯗꯣꯛꯎ ꯫",
    welcome: "SatQuery AI ꯗꯥ ꯇꯔꯥꯝꯅ ꯑꯣꯛꯆꯔꯤ",
    tagline: "ꯃꯂꯦꯝ ꯌꯦꯡꯁꯤꯅꯕ ꯑꯃꯁꯨꯡ ꯁ꯭ꯄꯦꯁꯤꯑꯦꯜ ꯑꯥꯏ.ꯀꯤ.ꯌꯨ"
  },
  {
    id: "brx",
    code: "brx",
    name: "Bodo",
    nativeName: "बर'",
    script: "Devanagari (देवनागरी)",
    category: "Scheduled (8th Schedule)",
    region: "Assam (Bodoland)",
    speakers: "1.5M",
    flag: "🇮🇳",
    samplePrompt: "सेटेलाइट डेटायाव दैलोनाय फिथाय दैथाय फोथार आरो सहरनि बांलाइनायखौ सिनायथि हो।",
    welcome: "SatQuery AI याव बरायबाय",
    tagline: "रोखा सेटेलाइट बुहुम नायलिरनाय आरो जायगायारि सोलोंथाय"
  },
  {
    id: "sa",
    code: "sa",
    name: "Sanskrit",
    nativeName: "संस्कृतम्",
    script: "Devanagari (देवनागरी)",
    category: "Scheduled & Classical",
    region: "Pan-India / Academic",
    speakers: "Classical",
    flag: "🇮🇳",
    samplePrompt: "उपग्रह-दत्तेषु जलप्लावितान् कृषि-भूभागान् नगर-विस्तारञ्च प्रत्यभिजानातु।",
    welcome: "सैट्क्वेरी ए-आई मञ्चे स्वागतम्",
    tagline: "सूक्ष्मतम बहु-प्रकार भू-निरीक्षणं भौगोलिकाभिज्ञानञ्च"
  },
  {
    id: "sd",
    code: "sd",
    name: "Sindhi",
    nativeName: "सिंधी / سنڌي",
    script: "Perso-Arabic / Devanagari",
    category: "Scheduled (8th Schedule)",
    region: "Gujarat, Rajasthan, Maharashtra",
    speakers: "2.8M",
    flag: "🇮🇳",
    samplePrompt: "سيٽلائيٽ ڊيٽا ۾ ٻوڏ متاثر زرعي زمينن ۽ شهري وسعت جي سڃاڻپ ڪريو.",
    welcome: "سيٽ ڪوئري AI ۾ ڀلي ڪري ۽",
    tagline: "باريڪ بيني سان ڌرتي جو مشاهدو ۽ جيو-اسپيشل ذھانت"
  },
  {
    id: "lbj",
    code: "lbj",
    name: "Ladakhi",
    nativeName: "ལ་དྭགས་སྐད་",
    script: "Tibetan (དབུ་ཅན་)",
    category: "North-East & Himalayan",
    region: "Ladakh UT",
    speakers: "110K",
    flag: "🇮🇳",
    samplePrompt: "སར་ཡིག་ ᱰᱟޓ ནང་ ཆུ་ལོག་ ཞིང་ཁ་ དང་ གྲོང་ཁྱེར་ རྒྱ་སྐྱེད་ ངོས་འཛིན་ བྱོས ༎",
    welcome: "SatQuery AI ལ་ བྱོན་པ་ ལེགས་སོ",
    tagline: "ས་གཞི་ ཞིབ་འཇུག་ དང་ མཁའ་དབྱིངས་ རིག་པ"
  },
  {
    id: "kha",
    code: "kha",
    name: "Khasi",
    nativeName: "Ka Ktien Khasi",
    script: "Latin",
    category: "North-East & Himalayan",
    region: "Meghalaya (Khasi Hills)",
    speakers: "1.6M",
    flag: "🇮🇳",
    samplePrompt: "Shephai ha ki dak satellite ia ki lyngkha ba tap um bad ka jingitynnad sor.",
    welcome: "Pdiang burom sha SatQuery AI",
    tagline: "Ka jingtip kaba bniah shaphang ka Khyndew bad ka Suinbneng"
  },
  {
    id: "grt",
    code: "grt",
    name: "Garo",
    nativeName: "A·chik",
    script: "Latin",
    category: "North-East & Himalayan",
    region: "Meghalaya (Garo Hills), Assam",
    speakers: "1.3M",
    flag: "🇮🇳",
    samplePrompt: "Satellite data-o chipa-gimin ge·ba-cha·ani a·ba aro songjinma bari·aniko ma·sichiani.",
    welcome: "SatQuery AI-ona rim·chaksoa",
    tagline: "A·song aro salgi nianida gimin tik-tak u·iani"
  },
  {
    id: "lus",
    code: "lus",
    name: "Mizo",
    nativeName: "Mizo ṭawng",
    script: "Latin",
    category: "North-East & Himalayan",
    region: "Mizoram",
    speakers: "1.2M",
    flag: "🇮🇳",
    samplePrompt: "Satellite data-a tuihliam lo ram leh khawpui zautir tawhte chhinchhiah rawh.",
    welcome: "SatQuery AI-ah chibai le",
    tagline: "Kan leilung thlir chianna leh hmunhma finna thiamna"
  }
];

export const DEFAULT_LANGUAGE = INDIAN_LANGUAGES[0]; // English
